# Generated by Django 3.1.4 on 2021-01-13 05:43

from django.db import migrations, models
import game.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("width", models.PositiveSmallIntegerField()),
                ("height", models.PositiveSmallIntegerField()),
                ("mines", models.PositiveSmallIntegerField()),
                (
                    "board",
                    models.JSONField(
                        decoder=game.models.BoardDecoder,
                        encoder=game.models.BoardEncoder,
                    ),
                ),
                (
                    "state",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Started"), (1, "Won"), (2, "Lost")]
                    ),
                ),
                ("date_started", models.DateTimeField(null=True)),
                ("date_ended", models.DateTimeField(null=True)),
            ],
        ),
    ]
